name: lin gds
on:
  push:
    branches: [ master- ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout vfd-gds
      uses: actions/checkout@v4
    - name: Checkout HDF5
      uses: actions/checkout@v4
      with:
        repository: HDFGroup/hdf5
        path: hdf5
    - name: Install dependencies
      run: sudo apt-get install ninja-build automake autoconf libtool libtool-bin libopenmpi-dev libpthread-stubs0-dev

    - name: Install CUDA        
      uses: Jimver/cuda-toolkit@master
    - name: Install HDF5
      run: |
        cmake --version
        mkdir hdf5/build
        cd hdf5/build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DHDF5_ENABLE_PARALLEL:BOOL=ON -DHDF5_ENABLE_THREADSAFE:BOOL=ON -DALLOW_UNSUPPORTED:BOOL=ON ..
        sudo make -j2 install
        cd ..
        git rev-parse HEAD > git.txt
      
    - name: Install vfd-gds
      env:
        HDF5_PLUGIN_PATH: /usr/local/lib
        LD_LIBRARY_PATH: /usr/local/lib:$LD_LIBRARY_PATH
        CUDACXX: /usr/local/cuda-12.6/bin/nvcc
      run: |
        set
        ls /usr/local/
        mkdir build
        cd build
        cmake .. -DHDF5_DIR=/usr/local
        sudo make -j2 install
        ls /usr/local/lib
        ctest --output-on-failure
